-- LeetCode Review Tracker — initial schema.
-- Six tables. The numeric LeetCode id is the stable PK for problems so upstream
-- slug/title renames never orphan progress. A nullable-free `user_id` slot
-- (default 1 = the single implicit user) is carried on per-user tables so auth
-- can be layered on later without a migration; no auth is wired now.

-- Enum-like values are stored as text and constrained with CHECK to match the
-- backend's Kotlin enum names exactly (see domain/enums.kt).

create table problems (
    id              bigint       primary key,            -- numeric LeetCode id (assigned, not generated)
    slug            varchar(255) not null unique,
    title           varchar(255) not null,
    difficulty      varchar(10)  not null check (difficulty in ('EASY', 'MEDIUM', 'HARD')),
    is_active       boolean      not null default true,
    is_neetcode_150 boolean      not null default false
);

create table tags (
    id   bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table problem_tags (
    problem_id bigint not null references problems (id) on delete cascade,
    tag_id     bigint not null references tags (id) on delete cascade,
    primary key (problem_id, tag_id)
);
create index idx_problem_tags_tag on problem_tags (tag_id);

create table user_progress (
    id               bigint generated by default as identity primary key,
    user_id          bigint      not null default 1,
    problem_id       bigint      not null references problems (id) on delete cascade,
    status           varchar(16) not null default 'TODO' check (status in ('TODO', 'REVIEW', 'MASTERED')),
    comfort          double precision,                   -- computed 1.0–5.0; null until first attempt
    stage            integer     not null default 0,     -- interval-ladder index 0..4
    last_reviewed_at timestamptz,
    next_review_at   timestamptz,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now(),
    unique (user_id, problem_id)
);
create index idx_user_progress_due on user_progress (user_id, next_review_at);

create table user_topic_comfort (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null default 1,
    tag_id     bigint      not null references tags (id) on delete cascade,
    rating     varchar(16) not null check (rating in ('COMFORTABLE', 'SHAKY', 'NOT_TRIED')),
    created_at timestamptz not null default now(),
    unique (user_id, tag_id)
);

create table review_sessions (
    id               bigint generated by default as identity primary key,
    user_id          bigint      not null default 1,
    problem_id       bigint      not null references problems (id) on delete cascade,
    outcome          varchar(24) not null check (outcome in ('SOLVED_CLEAN', 'SOLVED_HINTS', 'DIDNT_SOLVE')),
    peeked           boolean     not null default false,
    time_taken_min   integer,
    time_complexity  varchar(16),                        -- exact Big-O string, e.g. 'O(n)'
    space_complexity varchar(16),
    comfort_after    double precision,                   -- comfort recomputed after this session
    stage_after      integer,
    created_at       timestamptz not null default now()
);
create index idx_review_sessions_problem on review_sessions (user_id, problem_id, created_at desc);
