-- Auth: real per-user identity. Users get ids >= 1000 so a fresh login can never
-- collide with the orphaned single-user data at user_id = 1 (which is left as-is).

create table users (
    id         bigint generated by default as identity (start with 1000) primary key,
    email      text unique,
    name       text,
    avatar_url text,
    created_at timestamptz not null default now()
);

create table user_identities (
    id               bigint generated by default as identity primary key,
    user_id          bigint not null references users (id) on delete cascade,
    provider         text   not null check (provider in ('google', 'github')),
    provider_user_id text   not null,
    email            text,
    created_at       timestamptz not null default now(),
    unique (provider, provider_user_id)
);
create index idx_user_identities_user on user_identities (user_id);

create table sessions (
    token        text primary key,
    user_id      bigint not null references users (id) on delete cascade,
    created_at   timestamptz not null default now(),
    expires_at   timestamptz not null,
    last_seen_at timestamptz not null default now()
);
create index idx_sessions_user on sessions (user_id);

-- Auth is real now: a user-less write should fail loud, not silently land on the
-- orphaned single-user data. Existing user_id = 1 rows keep their value.
alter table user_progress      alter column user_id drop default;
alter table user_topic_comfort alter column user_id drop default;
alter table review_sessions    alter column user_id drop default;
